### ISSUE TITLE
Convert hooks into event emitter services

### ISSUE THREAD

**Issue by mrjmd** [mrjmd/decoupled_blocks#1]
The main pdb module is using old school hooks instead of even emitters, this needs to be fixed and the submodules for ng2 and react will need to be altered as well.

**Comment by emacoti** [comment]
PR: https://github.com/mrjmd/decoupled_blocks/issues/3

**Comment by mrjmd** [comment]
Looks great, thanks Emma!

**Comment by emacoti** [comment]
You're welcome!
