### ISSUE TITLE
Make it work on Drupal 8.1.x

### ISSUE THREAD

**Issue by mrjmd** [mrjmd/decoupled_blocks#16]
It appears that the latest D8 core breaks our module. :/ ... we need to investigate and fix it ASAP.

**Comment by mrjmd** [comment]
Apparently people are getting very mixed results here, so let's post our exact version numbers with what is / isn't working.

The behavior that some have reported is our example component blocks are not appearing for placement in either a) the core blocks UI, b) the panels UI, or c) both.

In my original build, where blocks are available in both core UI and Panels UI, I am using the following versions:

Drupal 8.0.4
Ctools 8.x-3.0-alpha23
Layout Plugin 8.x-1.0-alpha22
Page Manager 8.x-1.0-alpha23
Panels 8.x-3.0-beta4

**Comment by mark-casias** [comment]
No workie on:

Drupal 8.1.0-dev
ctools-8.x-3.0-alpha25
layout_plugin-8.x-1.0-alpha22
page_manager-8.x-1.0-alpha23
panels-8.x-3.0-beta4




Mark Casias
Sr Drupal Developer
T 678.580.1690 x212   F 770.360.5776
twitter <http://twitter.com/teampoop> • linkedin
<http://www2.mediacurrent.com/l/10072/2012-03-23/3qknq> • mediacurrent
<http://www2.mediacurrent.com/l/10072/2012-03-23/3qkpd>

**Comment by emacoti** [comment]
In my case, blocks are available in panels UI but not in core UI. Using the versions:

drupal 8.1.0 (April 19, 2016)
ctools 8.x-3.0-alpha25
layout plugin 8.x-1.0-alpha22
page Manager 8.x-1.0-alpha23
panels 8.x-3.0-beta4

**Comment by bjmac** [comment]
@emacoti how do you have your environment set up, are you using Vagrant, Drupal VM etc?

**Comment by emacoti** [comment]
@bjmac none of those, just a LEMP on my machine.

**Comment by derekreesemediacurrent** [comment]
Working for me in both, submitting a patch for @mark-casias 's Drupal VM so it names the module correctly.

Drupal 8.1.0
CTools 8.x-3.0-alpha25
Layout Plugin 8.x-1.0-alpha22
Page Manager 8.x-1.0-alpha23
Panels 8.x-3.0-beta4

**Comment by mark-casias** [comment]
Confirmed that after updating the path in my VM, this is working in 8.1.x..

**Comment by mrjmd** [comment]
Looks good, marking this done.
